export const CV_PDF_LAYOUT = {
  sidebarWidth: 190,
  pagePaddingTop: 28,
  pagePaddingBottom: 36,
  mainPaddingHorizontal: 22,
  sidebarPaddingHorizontal: 16,
  sidebarPaddingTop: 28,
  headerNameFontSize: 17,
  sectionTitleFontSize: 9.5,
  bodyFontSize: 8.5,
  sideBodyFontSize: 7.5,
  timelineItemMarginBottom: 6,
  recentDescriptionMaxChars: 180,
  pitchMaxChars: 280,
} as const
