/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    skills: Skill;
    experiences: Experience;
    qualifications: Qualification;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    qualifications: QualificationsSelect<false> | QualificationsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Comptes administrateurs uniquement — pas d’inscription publique.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Texte alternatif obligatoire (accessibilité + SEO).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Projets du portfolio (publics uniquement si published).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Généré automatiquement depuis le titre si laissé vide.
   */
  slug: string;
  excerpt: string;
  /**
   * Impact mesurable (ex. « 50+ utilisateurs · -30 % temps de traitement »).
   */
  impact?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  stack?:
    | (
        | 'nextjs'
        | 'react'
        | 'typescript'
        | 'payload'
        | 'nodejs'
        | 'postgres'
        | 'tailwind'
        | 'framer-motion'
        | 'vercel'
        | 'neon'
      )[]
    | null;
  liveUrl?: string | null;
  repoUrl?: string | null;
  featured?: boolean | null;
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  icon?: (number | null) | Media;
  category: 'frontend' | 'backend' | 'outils' | 'design' | 'soft';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  company: string;
  dateStart: string;
  dateEnd?: string | null;
  current?: boolean | null;
  /**
   * Affiché dans l’accordéon « Premières expériences » (parcours ancien).
   */
  earlyCareer?: boolean | null;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qualifications".
 */
export interface Qualification {
  id: number;
  title: string;
  institution?: string | null;
  year: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages reçus via le formulaire de contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'qualifications';
        value: number | Qualification;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  impact?: T;
  content?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  stack?: T;
  liveUrl?: T;
  repoUrl?: T;
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  dateStart?: T;
  dateEnd?: T;
  current?: T;
  earlyCareer?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qualifications_select".
 */
export interface QualificationsSelect<T extends boolean = true> {
  title?: T;
  institution?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identité (logo, favicon, avatar), réseaux sociaux et coordonnées.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline: string;
  /**
   * Portrait affiché dans le Hero et la page À propos.
   */
  avatar?: (number | null) | Media;
  /**
   * Logo du site (sidebar / header). PNG ou SVG carré recommandé.
   */
  logo?: (number | null) | Media;
  /**
   * Favicon navigateur (PNG 32×32 ou SVG).
   */
  favicon?: (number | null) | Media;
  email: string;
  socialLinks?:
    | {
        platform: 'github' | 'linkedin' | 'x' | 'dribbble' | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Override optionnel : PDF statique. Si vide, /api/cv génère le PDF dynamiquement.
   */
  cv?: (number | null) | Media;
  /**
   * Téléphone affiché sur le CV PDF.
   */
  phone?: string | null;
  /**
   * Projet professionnel / pitch long pour le CV PDF (sinon aboutIntro).
   */
  cvPitch?: string | null;
  /**
   * Citation de recommandation (CV PDF).
   */
  recommendationQuote?: string | null;
  /**
   * Auteur de la recommandation (ex. « Directeur Commercial, Entreprise X »).
   */
  recommendationAuthor?: string | null;
  /**
   * Ex. « Permis B — véhicule personnel, déplacements régionaux ».
   */
  mobility?: string | null;
  /**
   * Centres d'intérêt (CV PDF).
   */
  interests?: string | null;
  /**
   * Mention RQTH / aménagements (sensible — contrôlé par showRqthOnCv).
   */
  rqthNote?: string | null;
  showRqthOnCv?: boolean | null;
  /**
   * Langues pour le CV PDF.
   */
  languages?:
    | {
        name: string;
        level: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Compétences à niveau % pour le CV PDF (distinct des badges Skills).
   */
  cvCompetencies?:
    | {
        name: string;
        level: number;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Résumé court (Hero + intro À propos).
   */
  aboutIntro?: string | null;
  /**
   * Titre fort sous le profil (ex. « Profil Unique : La Polyvalence… »).
   */
  aboutHeadline?: string | null;
  /**
   * Texte long de la page À propos (CMS-first, pas de copy en dur).
   */
  aboutBody?: string | null;
  /**
   * Titre de la section Compétences (À propos).
   */
  skillsTitle?: string | null;
  /**
   * Sous-titre de la section Compétences (À propos).
   */
  skillsSubtitle?: string | null;
  /**
   * Ex. « La Rochelle · ouvert au remote ».
   */
  location?: string | null;
  /**
   * Badge de statut dans le Hero et le bandeau contact.
   */
  availability?: ('available' | 'limited' | 'unavailable') | null;
  /**
   * Libellé custom du badge (sinon libellé selon le statut).
   */
  availabilityLabel?: string | null;
  /**
   * Section « Approche » sur l’accueil (3 étapes recommandées).
   */
  approachSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Arguments différenciants (accordéon À propos).
   */
  whyMePoints?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Blocs compétences (accordéon À propos).
   */
  skillGroups?:
    | {
        title: string;
        /**
         * Une ligne par sous-compétence (ex. « Suite Adobe CC : Photoshop… »).
         */
        items: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Initiatives perso sur la page À propos.
   */
  personalProjects?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  defaultTitle: string;
  defaultDescription: string;
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  avatar?: T;
  logo?: T;
  favicon?: T;
  email?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  cv?: T;
  phone?: T;
  cvPitch?: T;
  recommendationQuote?: T;
  recommendationAuthor?: T;
  mobility?: T;
  interests?: T;
  rqthNote?: T;
  showRqthOnCv?: T;
  languages?:
    | T
    | {
        name?: T;
        level?: T;
        id?: T;
      };
  cvCompetencies?:
    | T
    | {
        name?: T;
        level?: T;
        description?: T;
        id?: T;
      };
  aboutIntro?: T;
  aboutHeadline?: T;
  aboutBody?: T;
  skillsTitle?: T;
  skillsSubtitle?: T;
  location?: T;
  availability?: T;
  availabilityLabel?: T;
  approachSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whyMePoints?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  skillGroups?:
    | T
    | {
        title?: T;
        items?: T;
        id?: T;
      };
  personalProjects?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}