/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'journal-posts': JournalPost;
    skills: Skill;
    experiences: Experience;
    qualifications: Qualification;
    tags: Tag;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    qualifications: QualificationsSelect<false> | QualificationsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
    'lablog-template': LablogTemplate;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'lablog-template': LablogTemplateSelect<false> | LablogTemplateSelect<true>;
  };
  locale: null;
  widgets: {
    'portfolio-welcome': PortfolioWelcomeWidget;
    'portfolio-stats': PortfolioStatsWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Comptes administrateurs uniquement — pas d’inscription publique.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Appareils autorisés à ouvrir /admin sans resaisir le mot de passe (gérés via le bandeau dashboard).
   */
  trustedDevices?:
    | {
        deviceId: string;
        label: string;
        secretHash: string;
        createdAt: string;
        lastUsedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Texte alternatif obligatoire (accessibilité + SEO).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Projets du portfolio (publics uniquement si published).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Généré automatiquement depuis le titre si laissé vide.
   */
  slug: string;
  excerpt: string;
  /**
   * Impact mesurable (ex. « 50+ utilisateurs · -30 % temps de traitement »).
   */
  impact?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  stack?:
    | (
        | 'nextjs'
        | 'react'
        | 'typescript'
        | 'payload'
        | 'nodejs'
        | 'postgres'
        | 'tailwind'
        | 'framer-motion'
        | 'vercel'
        | 'neon'
      )[]
    | null;
  /**
   * Tags transverses (SEO et filtrage futur).
   */
  tags?: (number | Tag)[] | null;
  liveUrl?: string | null;
  repoUrl?: string | null;
  /**
   * Projets suggérés en bas de fiche (publiés uniquement).
   */
  relatedProjects?: (number | Project)[] | null;
  featured?: boolean | null;
  order?: number | null;
  status: 'draft' | 'published';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * URL canonique override (laisser vide = URL auto).
     */
    canonicalURL?: string | null;
    /**
     * Exclure cette page des moteurs de recherche.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Tags transverses pour articles Lablog et projets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Généré depuis le nom si laissé vide.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles et galeries du Lablog (publics uniquement si published).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  /**
   * Article classique ou galerie d’images (grille ou diaporama).
   */
  postType: 'article' | 'gallery';
  title: string;
  /**
   * Généré automatiquement depuis le titre si laissé vide.
   */
  slug: string;
  excerpt: string;
  /**
   * Blueprint JSON (title, excerpt, category, blocks). À la sauvegarde, régénère le corps si le JSON a changé. Modèle de référence : Global « Modèle article Lablog ».
   */
  contentBlueprint?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Corps de l’article (non requis pour une galerie pure). Encarts info / attention / astuce disponibles.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover: number | Media;
  /**
   * Images de la galerie — affichées en grille ou diaporama.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Légende optionnelle (diaporama).
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Grille de vignettes ou diaporama plein écran.
   */
  galleryLayout?: ('grid' | 'slideshow') | null;
  category: 'ia' | 'design' | 'veille' | 'perso' | 'autre';
  /**
   * Tags transverses — filtrables sur /carnet?tag=slug
   */
  tags?: (number | Tag)[] | null;
  /**
   * Calculé automatiquement depuis l’extrait et le corps.
   */
  readingTimeMinutes?: number | null;
  publishedAt: string;
  status: 'draft' | 'published';
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * URL canonique override (laisser vide = URL auto).
     */
    canonicalURL?: string | null;
    /**
     * Exclure cette page des moteurs de recherche.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  icon?: (number | null) | Media;
  category: 'frontend' | 'backend' | 'outils' | 'design' | 'soft';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  company: string;
  dateStart: string;
  dateEnd?: string | null;
  current?: boolean | null;
  /**
   * Affiché dans l’accordéon « Premières expériences » (parcours ancien).
   */
  earlyCareer?: boolean | null;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qualifications".
 */
export interface Qualification {
  id: number;
  title: string;
  institution?: string | null;
  year: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages reçus via le formulaire de contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  message: string;
  /**
   * Suivi CRM minimal dans l’inbox.
   */
  inboxStatus: 'new' | 'read' | 'replied';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'qualifications';
        value: number | Qualification;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  trustedDevices?:
    | T
    | {
        deviceId?: T;
        label?: T;
        secretHash?: T;
        createdAt?: T;
        lastUsedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  impact?: T;
  content?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  stack?: T;
  tags?: T;
  liveUrl?: T;
  repoUrl?: T;
  relatedProjects?: T;
  featured?: T;
  order?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  postType?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  contentBlueprint?: T;
  content?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  galleryLayout?: T;
  category?: T;
  tags?: T;
  readingTimeMinutes?: T;
  publishedAt?: T;
  status?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  dateStart?: T;
  dateEnd?: T;
  current?: T;
  earlyCareer?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qualifications_select".
 */
export interface QualificationsSelect<T extends boolean = true> {
  title?: T;
  institution?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  inboxStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identité, contact, contenu éditorial, CV, mentions légales et options avancées — organisés par onglets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline: string;
  /**
   * Logo du site (sidebar / header). PNG ou SVG carré recommandé.
   */
  logo?: (number | null) | Media;
  /**
   * Favicon navigateur (PNG 32×32 ou SVG).
   */
  favicon?: (number | null) | Media;
  /**
   * Portrait affiché dans le Hero et la page À propos.
   */
  avatar?: (number | null) | Media;
  /**
   * Couleur barre navigateur (hex). Ex. #0a0a0a
   */
  themeColor?: string | null;
  email: string;
  /**
   * Téléphone affiché sur le CV PDF et les pages légales.
   */
  phone?: string | null;
  /**
   * Ex. « La Rochelle · ouvert au remote ».
   */
  location?: string | null;
  /**
   * Badge de statut dans le Hero et le bandeau contact.
   */
  availability?: ('available' | 'limited' | 'unavailable') | null;
  /**
   * Libellé custom du badge (sinon libellé selon le statut).
   */
  availabilityLabel?: string | null;
  socialLinks?:
    | {
        platform: 'github' | 'linkedin' | 'x' | 'dribbble' | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sous-titre de la page Contact (sinon email affiché).
   */
  contactPageSubtitle?: string | null;
  enableContactForm?: boolean | null;
  /**
   * Résumé court (Hero + intro À propos).
   */
  aboutIntro?: string | null;
  /**
   * Titre fort sous le profil (ex. « Profil Unique : La Polyvalence… »).
   */
  aboutHeadline?: string | null;
  /**
   * Texte long de la page À propos (CMS-first, pas de copy en dur).
   */
  aboutBody?: string | null;
  /**
   * Titre de la section Compétences (À propos).
   */
  skillsTitle?: string | null;
  /**
   * Sous-titre de la section Compétences (À propos).
   */
  skillsSubtitle?: string | null;
  /**
   * Section « Approche » sur l’accueil (3 étapes recommandées).
   */
  approachSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Arguments différenciants (accordéon À propos).
   */
  whyMePoints?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Blocs compétences (accordéon À propos).
   */
  skillGroups?:
    | {
        title: string;
        /**
         * Une ligne par sous-compétence (ex. « Suite Adobe CC : Photoshop… »).
         */
        items: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Initiatives perso sur la page À propos.
   */
  personalProjects?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Override optionnel : PDF statique. Si vide, /api/cv génère le PDF dynamiquement.
   */
  cv?: (number | null) | Media;
  /**
   * Intitulé de poste sous le nom sur le CV (ATS). Ex. « Chargé de Clientèle & Projets Digitaux | Commercial B2B ».
   */
  cvJobTitle?: string | null;
  /**
   * Projet professionnel / pitch long pour le CV PDF (sinon aboutIntro).
   */
  cvPitch?: string | null;
  /**
   * Ex. « Permis B — véhicule personnel, déplacements régionaux ».
   */
  mobility?: string | null;
  /**
   * Centres d'intérêt (CV PDF).
   */
  interests?: string | null;
  /**
   * Mention RQTH / aménagements (sensible — contrôlé par showRqthOnCv).
   */
  rqthNote?: string | null;
  showRqthOnCv?: boolean | null;
  /**
   * Langues pour le CV PDF.
   */
  languages?:
    | {
        name: string;
        level: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Catégories de compétences textuelles pour le CV (ATS) — sans pourcentages ni jauges.
   */
  cvCompetencies?:
    | {
        name: string;
        /**
         * Séparer par virgules ou retours à la ligne (ex. Prospection B2B/B2C, CRM, Relation Client).
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Éditeur du site (mentions légales). Par défaut : nom du site.
   */
  legalPublisher?: string | null;
  /**
   * Directeur de la publication (mentions légales).
   */
  legalDirector?: string | null;
  /**
   * Bloc hébergeur (une ligne par prestataire). Ex. « Vercel Inc. — vercel.com ».
   */
  legalHostingProvider?: string | null;
  /**
   * Ligne optionnelle sous le copyright du footer.
   */
  footerExtraLine?: string | null;
  /**
   * Liens affichés dans le footer (ex. mentions légales, confidentialité, GitHub). Si vide, les liens légaux par défaut sont utilisés.
   */
  footerLinks?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Libellé navigation (sidebar / mobile).
   */
  journalNavLabel?: string | null;
  /**
   * Titre H1 page listing.
   */
  journalTitle?: string | null;
  journalEyebrow?: string | null;
  journalSubtitle?: string | null;
  /**
   * Articles Lablog mis en avant sur l’accueil (max 3).
   */
  featuredJournalPosts?: (number | JournalPost)[] | null;
  maintenanceMode?: boolean | null;
  /**
   * Message affiché dans le bandeau maintenance.
   */
  maintenanceMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Balises meta, Open Graph, Twitter, indexation et JSON-LD — organisés par onglets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * Titre par défaut (accueil et fallback des pages).
   */
  defaultTitle: string;
  /**
   * Meta description par défaut (160 caractères max).
   */
  defaultDescription: string;
  /**
   * Modèle pour les pages internes. Utilisez %s pour le titre de page.
   */
  titleTemplate?: string | null;
  /**
   * Mots-clés séparés par des virgules (meta keywords).
   */
  keywords?: string | null;
  /**
   * Image Open Graph par défaut (1200×630 recommandé).
   */
  ogImage?: (number | null) | Media;
  /**
   * Locale Open Graph (ex. fr_FR).
   */
  ogLocale?: string | null;
  /**
   * Nom du site pour Open Graph (sinon nom du site).
   */
  ogSiteName?: string | null;
  twitterCard?: ('summary_large_image' | 'summary') | null;
  /**
   * Compte du site (@handle).
   */
  twitterSite?: string | null;
  /**
   * Créateur / auteur (@handle).
   */
  twitterCreator?: string | null;
  /**
   * Utile pour les previews ou environnements de staging.
   */
  noindexSite?: boolean | null;
  robotsIndex?: boolean | null;
  robotsFollow?: boolean | null;
  /**
   * Code de vérification Google Search Console (meta tag).
   */
  googleSiteVerification?: string | null;
  /**
   * URL canonique de base (override). Laissez vide pour NEXT_PUBLIC_SITE_URL / domaine courant.
   */
  canonicalBaseUrl?: string | null;
  enablePersonJsonLd?: boolean | null;
  enableWebsiteJsonLd?: boolean | null;
  /**
   * Nom de l’auteur pour les données structurées (sinon nom du site).
   */
  schemaAuthorName?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Schéma JSON de référence pour générer des articles conformes à la direction artistique du Lablog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lablog-template".
 */
export interface LablogTemplate {
  id: number;
  /**
   * Structure JSON à reproduire (title, excerpt, category, blocks). Utilisable par une IA ou copié dans le champ « Blueprint JSON » d’un article.
   */
  jsonTemplate:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Consignes pour la génération IA ou rédaction assistée.
   */
  generationHints?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  avatar?: T;
  themeColor?: T;
  email?: T;
  phone?: T;
  location?: T;
  availability?: T;
  availabilityLabel?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  contactPageSubtitle?: T;
  enableContactForm?: T;
  aboutIntro?: T;
  aboutHeadline?: T;
  aboutBody?: T;
  skillsTitle?: T;
  skillsSubtitle?: T;
  approachSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whyMePoints?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  skillGroups?:
    | T
    | {
        title?: T;
        items?: T;
        id?: T;
      };
  personalProjects?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cv?: T;
  cvJobTitle?: T;
  cvPitch?: T;
  mobility?: T;
  interests?: T;
  rqthNote?: T;
  showRqthOnCv?: T;
  languages?:
    | T
    | {
        name?: T;
        level?: T;
        id?: T;
      };
  cvCompetencies?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  legalPublisher?: T;
  legalDirector?: T;
  legalHostingProvider?: T;
  footerExtraLine?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  journalNavLabel?: T;
  journalTitle?: T;
  journalEyebrow?: T;
  journalSubtitle?: T;
  featuredJournalPosts?: T;
  maintenanceMode?: T;
  maintenanceMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  titleTemplate?: T;
  keywords?: T;
  ogImage?: T;
  ogLocale?: T;
  ogSiteName?: T;
  twitterCard?: T;
  twitterSite?: T;
  twitterCreator?: T;
  noindexSite?: T;
  robotsIndex?: T;
  robotsFollow?: T;
  googleSiteVerification?: T;
  canonicalBaseUrl?: T;
  enablePersonJsonLd?: T;
  enableWebsiteJsonLd?: T;
  schemaAuthorName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lablog-template_select".
 */
export interface LablogTemplateSelect<T extends boolean = true> {
  jsonTemplate?: T;
  generationHints?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-welcome_widget".
 */
export interface PortfolioWelcomeWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-stats_widget".
 */
export interface PortfolioStatsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}